# /api/v1/namespaces/{namespace}/pods にリクエストを投げる
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: hello-app-container
    # コンテナイメージを指定
    image: rhanafusa/hello-app:1.0

