# /apis/apps/v1/namespaces/{namespace}/replicasets にリクエストを投げる
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-example
spec:
  replicas: 3
  selector:
    # labelの検索条件
    matchLabels:
      app: hello-app
  template:
    # template以下がPodとほとんど同じ
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app-container
          image: rhanafusa/hello-app:1.0

