apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-example
spec:
  replicas: 3
  selector:
    # labelの検索条件
    matchLabels:
      app: example
  template:
    # template以下がPodとほとんど同じ
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12

