apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-deployment
spec:
  ## ローリングアップデートの設定 ##
  # 新規作成されたPodがReadyになってから起動成功と判断するまでの猶予時間
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 1台ずつ更新していく
      maxSurge: 1
      maxUnavailable: 0
  ##############################
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12

