## シンプルなServiceの定義
apiVersion: v1
kind: Service
metadata:
  name: service-example
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    # 8080番ポートに受けて各Podの8080番ポートに転送する
    port: 8080
    targetPort: 8080
  selector:
    # Deploymentと同じラベルをつける
    app: hello-app
---
## Serviceに対応したDeploymentを定義
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app-container
        image: rhanafusa/hello-app:1.0
        # コンテナのポートを指定
        ports:
        - containerPort: 8080

